export const SEND_MOVIE = "SEND_MOVIE";
export const DELET_FILM = "DELET_FILM";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SAVE_IN_LIST = "SAVE_IN_LIST";
export const SAVE_IN_FAVORITS = "SAVE_IN_FAVORITS";
export const SAVE_FAVORIT_LIST_ID = "SAVE_FAVORIT_LIST_ID";
export const GET_FAVORIT_FILMS_ID = "GET_FAVORIT_FILMS_ID";
export const SAVE_ALL_FAVORIT_FILMS = "SAVE_ALL_FAVORIT_FILMS";
